docker pull kollaglue/fedora-rdo-keystone                                          
docker pull kollaglue/centos-rdo-keystone                                          
docker pull kollaglue/fedora-rdo-nova-compute                                      
docker pull kollaglue/fedora-rdo-base                                              
docker pull kollaglue/fedora-rdo-nova-api                                          
docker pull kollaglue/fedora-rdo-mariadb                                           
docker pull kollaglue/centos-rdo-nova-network                                      
docker pull kollaglue/centos-rdo-rabbitmq                                          
docker pull kollaglue/fedora-rdo-nova-base                                         
docker pull kollaglue/centos-rdo-horizon                                           
docker pull kollaglue/centos-rdo-nova-libvirt                                      
docker pull kollaglue/fedora-rdo-nova-network                                      
docker pull kollaglue/centos-rdo-nova-compute                                      
docker pull kollaglue/fedora-rdo-glance-registry                                   
docker pull kollaglue/fedora-rdo-glance-api                                        
docker pull kollaglue/fedora-rdo-nova-scheduler                                    
docker pull kollaglue/fedora-rdo-nova-conductor                                    
docker pull kollaglue/centos-rdo-base                                              
docker pull kollaglue/centos-rdo-nova-base                                         
docker pull kollaglue/fedora-rdo-nova-libvirt                                      
docker pull kollaglue/fedora-rdo-rabbitmq                                          
docker pull kollaglue/fedora-rdo-heat-engine                                       
docker pull kollaglue/fedora-rdo-heat-api                                          
docker pull kollaglue/fedora-rdo-glance-base                                       
docker pull kollaglue/fedora-rdo-l3   
